### ISSUE TITLE
Wie bekommt man Content auf den Pi?

### ISSUE THREAD

**Issue by 205er** [ToolboxBodensee/info-display-ruum-42#1]
Hallo!

ich hätte ein paar Dinge, die ich gern auf dem Info-Display sehen würde.
Was muss man denn tun, um Content auf den pi zu bekommen? Hängt der am Netz? Muss man die SD-Card direkt beschreiben? Gibt's irgendwo ein HowTo (für die TB-Installation)? Oder kann man Irgendwen direkt ansprechen? Wiki-Artikel dazu wäre cool (würde ich auch schreiben, wenn ich die Infos hätte) ;-) 

Grüße

**Comment by DEvil0000** [comment]
Repo ist noch keine 12h online und schon fragst du - nice! So war der plan.
Das PI hängt am netz. Ein cron job macht git pull vom master.
Infos wie man was ändert findest du sonst am ehesten hier: https://info-beamer.com/doc/info-beamer

**Comment by 205er** [comment]
Danke, l3d!!!

@DEvil0000 Warum sollte ich das nicht fragen? Das Display hängt da übrigens schon eine gefühlte Ewigkeit und ich hatte bereits verschiedene Leute angesprochen, um in Erfahrung zu bringen wie man da was ändern kann... bisher leider ohne Erfolg!
